---
title: "UTA100"
output: html_notebook
---

```{r setup}
library(tabulizer)
library(tidyverse)
library(lubridate)

source("scripts/time-funs.R")
```


```{r cache=TRUE}
uta100_raw <- tabulizer::extract_tables("input/uta_2018_classement_UTA100_scratch.pdf") 
```


```{r}
cols <- c("rank", "bib", "name", "club", "cat", "rank_cat", "time", "diff_time", "country")

uta100 <- uta100_raw[1:27] %>% map(function(x) x[-1, ]) %>% map(as.tibble) %>% bind_rows() %>% select(-(10:11)) %>% set_names(cols)
tail_page <- uta100_raw[[28]][-(1:2),] %>% as.tibble() %>% select(-c(4, 6)) %>% set_names(cols)

uta100 <- uta100 %>% bind_rows(tail_page)

names(uta100) <- cols

uta100 <- uta100 %>% filter(cat != 9 & cat != "") %>% mutate(rank = as.numeric(rank), time = as.numeric(hms(time), units = "sec"))

jpn <- uta100 %>% filter(country == "Japanese")
```

```{r}
uta_scale <- pretty_seq(uta100$time)
ggplot(uta100, aes(time)) + geom_histogram(binwidth = 1800) + geom_vline(xintercept = 14 * 3600, color = 'red') + scale_x_continuous(breaks = uta_scale, labels = pretty_time(uta_scale)) + theme_bw()
```

```{r}
n_below <- sum(uta100$time < 3600 * 14, na.rm = TRUE)
n_finished <- sum(!is.na(uta100$time))

rate <- format(n_below / n_finished * 100, digits = 3)

ggplot(uta100, aes(time, rank)) + geom_line() + geom_vline(xintercept = 14 * 3600, color = 'red') + scale_x_continuous(breaks = uta_scale, labels = pretty_time(uta_scale)) + theme_bw() +
  labs(title = paste0("Only ", rate, "% of the finishers complete the race within 14hrs"))
```

```{r}
load("interim/utmf2018-fixed2.RData")

deconvolute_names <- function(nms){
  processed <- str_to_lower(nms) %>% str_split(" ") %>% map(sort) %>% map(function(x) x[x != ""]) %>% 
    map(str_trim) %>% map(str_squish) %>% map_chr(paste, collapse = " ")
  processed
}


utmf2018_simple <- utmf2018_all %>% select(name_en, Finish)

utmf2018_simple <- utmf2018_simple %>% mutate(name_vec = deconvolute_names(name_en))
uta100 <- uta100 %>% mutate(name_vec = deconvolute_names(name))

both_races <- uta100 %>% inner_join(utmf2018_simple, by = "name_vec", suffix = c("uta", "utmf"))

uta_scale2 <- seq(0, 24, 2) * 3600

ggplot(both_races, aes(Finish, time)) + geom_point() + geom_smooth(method = "glm") + scale_y_continuous(limits = c(0, 24) * 3600, breaks = uta_scale2, labels = pretty_time(uta_scale2)) + 
  scale_x_continuous(breaks = seq(20, 46, 2) * 3600, labels = pretty_time(seq(20, 46, 2) * 3600))
```

